[package]
name = "pingx"
version = "0.1.2"
edition = "2024"
authors     = ["Seamile <lanhuermao@gmail.com>"]
license     = "MIT"
description = "一款简单实用的网络诊断工具，可用于代替系统的 ping 和 ping6 命令，支持 ICMP、TCP、HTTP 协议。"
homepage    = "https://github.com/seamile/pingx"
repository  = "https://github.com/seamile/pingx"
keywords    = ["cli", "tool", "ping", "network"]
categories  = ["command-line-utilities"]
readme      = "README.md"

[[bin]]
name = "pingx"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12.28", features = ["rustls-tls"], default-features = false }
anyhow = "1.0"
thiserror = "2.0.17"
async-trait = "0.1"
futures = "0.3"
surge-ping = "0.8"
colored = "3.0.0"
