[package]
name = "pingx"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pingx"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
surge-ping = "0.8"
