[build]
rustc-wrapper = "sccache"

[target.x86_64-apple-darwin]
rustflags = ["-C", "split-debuginfo=unpacked"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "split-debuginfo=unpacked"]

[registries.crates-io]
protocol = "sparse"
